### ISSUE TITLE
Bug: label of last point changes when selecting new point

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#10]
If label switching via the left mouse is activated and a new point is being selected, the label of the point that has been selected switches.

I guess [this check](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L119) needs to be adapted to recognize that a new point is being selected and not switch labels in that case.

Another option would be to switch labels with right click.

**Comment by constantinpape** [comment]
@kevinyamauchi any tips on how to either fix the check or use right click for switching instead?

**Comment by kevinyamauchi** [comment]
Hey. You can get the indices of the selected points being selected with `point_layer.selected_data` (returns a set of the indices). Perhaps you could check if the selected point is a different point than the one previously selected.

Another option is to use a modifier key. For example if you hold alt, you append the label iterating callback and then when you  release alt, you remove the label iterating callback. See how we use the space bar to change the mode when it is held down as an example ([here](https://github.com/napari/napari/blob/e1e1c44b09c91401ce4a348bbd0f1b3ef6b9ac20/napari/layers/points/_points_key_bindings.py#L6-L19)).

**Comment by constantinpape** [comment]
> Hey. You can get the indices of the selected points being selected with `point_layer.selected_data` (returns a set of the indices). Perhaps you could check if the selected point is a different point than the one previously selected.

I tried to implement this, see https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L128-L136. However, it doesn't change the behaviour.

I think the reason for this is the order in which the actions are received after left click
1. `next_on_click` is triggered and the label change is done
2. the current point is de-selected and the new point is selected
So when [this check](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L131) is performed, it passes because the selection has not been updated yet.

Any idea on how to fix this? Can we modify the order of events?

> Another option is to use a modifier key.

If possible we would like to keep it on simple left click. Also, I tried the space modifier for panning (which in principle is a cool feature!), but it doesn't work that well for me. See https://github.com/napari/napari/issues/1282.

**Comment by kevinyamauchi** [comment]
> Any idea on how to fix this? Can we modify the order of events?

The mouse press bindings are stored in a list (`layer.mouse_drag_callbacks`) and re-ordering them in the list, reorders the order of execution (I believe they are executed in order of index).

Since it is a list, you can find the index of your callback function with (from https://github.com/hci-unihd/covid-if-annotations/issues/2#issuecomment-633022897) 
```python
points_layer.mouse_drag_callbacks.index(next_on_click)
```

The mouse click callback that selects the point is here: https://github.com/napari/napari/blob/a83fef5f9fa27496eb5a5912f0fc274221794d13/napari/layers/points/_points_mouse_bindings.py#L6-L83

In your case, it seems like you want the point selection/deselection done first and then the label iterated, so perhaps you could try to add some logic to set the callback function order properly. 

In the snippet I posted [here](https://github.com/hci-unihd/covid-if-annotations/issues/2#issuecomment-633022897), I took a quick stab towards this, but I didn't test it much so I don't know how well it works. The `set_toggle_mode()` function would set the layer up with the mouse click callbacks ordered: first select/deselect points and then call the label iteration function. That is, the user would press the `t` key to enter the mode allowing them to iterate through labels by clicking with the correct callback order. Of course, this wouldn't prevent the user from just entering the `selection` mode from the GUI and clicking with potentially the wrong callback order. To try and address this, in the label iteration function (`next_on_click()`), it only iterates when it is not the first callback.

Sorry, this is a bit of a brain dump. Do any of these ideas/thoughts help?

Figuring out the best way to expose keybindings to plugin developers is an active discussion here: https://github.com/napari/napari/issues/1272. If you haven't already, it would be great if you weighed in with some of your thoughts/experiences!

**Comment by constantinpape** [comment]
> Sorry, this is a bit of a brain dump. Do any of these ideas/thoughts help?

Yes, I think the problem now is that the `next_on_click` mouse binding is now attached to the viewer, not to the points layer anymore.
I will see if I can add it to the points layer instead.

**Comment by constantinpape** [comment]
Ok, I have fixed this now by moving the click binding to the points layer and introducing 
https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L145-L148
to make sure that the `next_on_click` is always the last callback.
Thanks for your help @kevinyamauchi!

**Comment by kevinyamauchi** [comment]
Great! Nice work!
