### ISSUE TITLE
Use point layer for semantic annotations

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#2]
To make correcting the cell segmentation efficient in step 1 (see #1), we would need to be able to
hide cells that have already been corrected, or have been inspected and deemed as correct.
Otherwise users would likely visit the same cells all over again and it would be difficult to tell when to stop.

**Comment by sofroniewn** [comment]
Do you have a corresponding "instance segmentation" mask that matches the semantic segmentation mask you have in this image?

![image](https://user-images.githubusercontent.com/6531703/82720110-529ef300-9c65-11ea-9539-240537aa1813.png)

i.e. instead of just the class one and class two, I want the pixels corresponding to each cell boundary to have a different id, 1, 2, 3 ....

It seems like that would be very useful in this context.

One could then level a points layer with points located at the centroid of each cell to do the assignment/ classification (step 2). This could be much faster/ easier more UI friendly than working with the labels layer. We could also think about how to synchronize the points layer with the labels layer so that changing the class of the point could change the label from being visible to not.

![image](https://user-images.githubusercontent.com/6531703/82720208-086a4180-9c66-11ea-8c53-12676e087147.png)

The approach I am imaging would have 3 annotation type layers. One is instance labels, one is semantic labels, one is points located at the centroids of the instance labels.

If there was a segmentation error you would see it in instance labels and you would correct it with the paintbrush there. This would automatically update the semantic labels based on the new contours and the points class. One the boundaries are all perfect you could use the points layer to annotate the centroids (cells) as "infected", "control" or "uncertain". You could also have an additional category for "inspected" or "not" which could hide the contours of the semantic labels layer as desired.

Let me know if any of this is making sense/ seems like the right approach

**Comment by sofroniewn** [comment]
See code inside https://github.com/napari/napari/blob/master/examples/add_points_with_properties.py for an example of a points layer with properties, we'd need to provide some additional UI code to allow you to change the class of the points via selection, but @kevinyamauchi has examples of that in other places that I'm sure he would share, and I think will be integrating functionality like that into napari by default fairly soon regardless

**Comment by constantinpape** [comment]
Yes, we start from an instance segmentation:

![Screenshot from 2020-05-23 09-59-52](https://user-images.githubusercontent.com/4263537/82725363-b4e70a80-9cdc-11ea-9089-e8799cd7d1c8.png)

The semantic classification into infected vs control is then derived from this instance segmentation,
and I have turned it into the "edge layer" for visualization:

![Screenshot from 2020-05-23 09-59-46](https://user-images.githubusercontent.com/4263537/82725383-e9f35d00-9cdc-11ea-8d4b-78151f1c5438.png)

(For the final annotation tool, we would leave the semantic classification uninitialized, because we don't want to bias the annotations; but for the prototype I have initialized it with the results from our automatic (heuristic-based) classification).

> The approach I am imaging would have 3 annotation type layers. One is instance labels, one is semantic labels, one is points located at the centroids of the instance labels.
> 
> If there was a segmentation error you would see it in instance labels and you would correct it with the paintbrush there. This would automatically update the semantic labels based on the new contours and the points class. One the boundaries are all perfect you could use the points layer to annotate the centroids (cells) as "infected", "control" or "uncertain". You could also have an additional category for "inspected" or "not" which could hide the contours of the semantic labels layer as desired.
> 
> Let me know if any of this is making sense/ seems like the right approach

This makes perfect sense and is much better than using a labels layer for the semantic annotations.
I think if this works intuitively we don't even need to separate steps 1 and 2 so strictly.
We initially decided to have a clean separation between the two steps to avoid ambiguities when mapping between labels for the classification and the instance segmentation.

So yes, I believe this is the way to go, I will have a look at the code you shared later and see if I can get started with this already.

**Comment by constantinpape** [comment]
Ok, one more questions right away:
Is it possible to toggle through a range of values associated with a point in the points layer just by clicking on it?
In our case that would be:
`unlabeled` (which is how every segment / point is initialized), `infected`, `control`, `uncertain`.
(And additionally maybe `hidden` to keep track of objects that have already been labeled; but this is a bit more tricky, because it should not override the semantic tag.)

**Comment by kevinyamauchi** [comment]
Hello @constantinpape - it's nice to meet you! I believe you should be able to cycle through property values of a particular point by clicking on it.

I have a work in progress tutorial that gets features cycling property values and modifying property values of selected points. You can see the pull request [here](https://github.com/napari/tutorials/pull/62), to get an idea (in particular, see the "Keybindings for switching labels" and "Mousebinding to iterate through labels" sections in [`annotating_points.md`](https://github.com/napari/tutorials/blob/248d127d39259e9d425d4bc59c560d174583b868/applications/annotate_points.md)). If there are any bits that are unclear or could be improved, it would be super helpful if you could drop a comment in the PR! The code described in the tutorial can be found [here](https://github.com/kevinyamauchi/PointAnnotator). I believe it works on the current master, but it was on my to do list to update it this weekend anyway, so I will do it today.

For your particular idea to cycle upon clicking, I think you can do something like the snippet I pasted below. Unfortunately, we don't have a way of ensuring key/mouse binding callback order at the moment, so there's a bit of hacky code in there to ensure the mouse click callback is called after the point is selected.

Basically, the mouse click callbacks are a `List` of the callback functions stored in `points_layer.mouse_drag_callbacks` and we need to make sure that our point label iterating function (`next_label()`) gets called last, after the callback function that determines which point was selected is called. To ensure this, I made a function (`set_toggle_mode()`) that properly sets up the callbacks (bound to the `t` key). Additionally, I added some logic to the mouse click callback to try to make sure it only tries to iterates the point labels when the callbacks are in the right order (I haven't tested extensively - may have missed some edge cases). I am glad you mentioned this use case because I think it highlights a couple of things for controlling the interactivity of `napari` that we need to expose to plugin developers: (1) better control over keybindings (@sofroniewn even already made an [issue](https://github.com/napari/napari/issues/1272)!) and (2) better control over interaction modes (e.g., it would be nice to be able to lock the user out of the ability to add points).

In any case, I think this should get you started. Let me know if this is what you have in mind and/or if you have any questions!

<details>

<summary> <b>example code</b> </summary>

```python
import numpy as np
from skimage import data
from skimage.color import rgb2gray
import napari


with napari.gui_qt():
    # list of possible label values
    labels = ['infected', 'control', 'uncertain']

    # add the image
    viewer = napari.view_image(rgb2gray(data.astronaut()))
    # add the points
    points = np.array([[100, 100], [200, 200], [333, 111]])

    # create properties for each point
    properties = {
        'confidence': np.array([1, 0.5, 0]),
        'cell_type': np.array(['infected', 'control', 'uncertain'])
    }

    # define the color cycle for the face_color annotation
    face_color_cycle = ['blue', 'green', 'magenta']

    # create a points layer where the face_color is set by the good_point property
    # and the edge_color is set via a color map (grayscale) on the confidence property.
    points_layer = viewer.add_points(
        points,
        properties=properties,
        size=20,
        edge_width=7,
        edge_color='black',
        edge_colormap='gray',
        face_color='cell_type',
        face_color_cycle=face_color_cycle
    )

    
    @viewer.bind_key('.')
    def next_label(event=None):
        """Keybinding to advance to the next label value in
        the labels list (defined near the top) with wraparound

        Setting the values in points_layer.current_properties modifies the property
        values for the currently selected points and also will be the values used for
        the next points that are added.
        """
        # get the current properties and cell type value
        current_properties = points_layer.current_properties
        current_label = current_properties['cell_type'][0]
        
        # get the next label value with wraparound
        ind = list(labels).index(current_label)
        new_ind = (ind + 1) % len(labels)
        new_label = labels[new_ind]

        # set the new cell type value and update the current_properties
        current_properties['cell_type'] = np.array([new_label])
        points_layer.current_properties = current_properties

    
    def next_on_click(layer, event):
        """Mouse click binding to advance the label of the selected point"""
        # only perform toggling if in the selection mode and there are points selected
        if (layer.mode == 'select') and (len(layer.selected_data) > 0):
            # check that the mouse click callback is in the right position
            if points_layer.mouse_drag_callbacks.index(next_on_click) > 0:
                next_label()

    
    @viewer.bind_key('t')
    def set_toggle_mode(event=None):
        """Keybinding to set the viewer selection mode and mouse callbacks
        for toggling selected points properties by clicking on them
        """
        if next_on_click in points_layer.mouse_drag_callbacks:
            points_layer.mouse_drag_callbacks.remove(next_on_click)
        points_layer.mode = 'select'
        points_layer.mouse_drag_callbacks.append(next_on_click)

    set_toggle_mode()
```

</details>

**Comment by akreshuk** [comment]
> Ok, one more questions right away:
> Is it possible to toggle through a range of values associated with a point in the points layer just by clicking on it?
> In our case that would be:
> `unlabeled` (which is how every segment / point is initialized), `infected`, `control`, `uncertain`.
> (And additionally maybe `hidden` to keep track of objects that have already been labeled; but this is a bit more tricky, because it should not override the semantic tag.)

We could also make a general checkbox on the left, like "hide already labeled objects" and then they are optionally all gone / grayed out/ covered with a semi-transparent black overlay. If one feels like going back, it's ok if they all come back on for that, as long as you can hide them again with this switch. I can even imagine it more fine-grained: general switch, and then a right-click context menu for each object which would have an option like "never hide". If the object is already labeled, the first click on it doesn't change the label, but makes it visible again. Or would that be too confusing?

**Comment by constantinpape** [comment]
@kevinyamauchi Nice to meet you too!
And thanks for the explanation, I think that's exactly what I need, I will give it a try later and let you know how it works / if I run into any issues.

@akreshuk 
> We could also make a general checkbox on the left, like "hide already labeled objects" and then they are optionally all gone / grayed out/ covered with a semi-transparent black overlay. If one feels like going back, it's ok if they all come back on for that, as long as you can hide them again with this switch.

I agree, this is a really good solution and it should be simple to implement.
I would leave it at the simple solution you propose for now, I think the more fine-grained option would be too confusing (and also more complicated to implement.)

**Comment by kevinyamauchi** [comment]
No problem! Please feel free to reach out if you run into any issues.

**Comment by constantinpape** [comment]
@kevinyamauchi 
Based on your code I have associated labels with the points layer now and also got the `.` key for label toggling to work. I haven't checked toggling by mouse, gonna do that tomorrow.
I have one question though: what are the `confidence` values for? Do they have any effect in the current code?

**Comment by sofroniewn** [comment]
> I have one question though: what are the confidence values for? Do they have any effect in the current code?

Are you referring to `confidence` in this example [add_points_with_properties.py](https://github.com/napari/napari/blob/master/examples/add_points_with_properties.py)? In this example they are coloring `edge_color`, but it was really arbitrary and I think only meant to illustrate that one could have multiple keys inside the `properties` dictionary and use them differently (or even ignore them). I imagine that's similar for whatever code you're looking at - but I'll let @kevinyamauchi clarify

**Comment by constantinpape** [comment]
[The code example @kevinyamauchi shared here](https://github.com/hci-unihd/covid-if-annotations/issues/2#issuecomment-633022897) also contains the `confidence` variables. It's probably just a remainder from the code he based this on, just wanted to make sure ;).

**Comment by kevinyamauchi** [comment]
>  The code example @kevinyamauchi shared here also contains the confidence variables. It's probably just a remainder from the code he based this on, just wanted to make sure ;).

@constantinpape , you are correct. The 'confidence' property is just carryover. I had included it to demonstrate you can associate multiple properties with each point, even if you are only using a subset for setting display parameters (e.g., face color), but I should have mentioned that. Sorry for the confusion!

It sounds like you're on the right track, but let me know if you end up having some trouble with the mouse part.

**Comment by constantinpape** [comment]
> @constantinpape , you are correct. The 'confidence' property is just carryover. I had included it to demonstrate you can associate multiple properties with each point, even if you are only using a subset for setting display parameters (e.g., face color), but I should have mentioned that. Sorry for the confusion!

No worries and thanks for the clarification.

> It sounds like you're on the right track, but let me know if you end up having some trouble with the mouse part.

Ok, I adapted your code for the mouse clicking now, but still have one issue:
I integrated it into the [_key_bindings.py](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py), which is based on the `segmentify` example shared by @sofroniewn in #3.
However, I need to pass the `viewer` to `next_label` in `next_on_click` now, and I don't know what's the best way to do this.
See https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L100-L101 for details.

Thanks!

**Comment by constantinpape** [comment]
@kevinyamauchi I found another issue: the color mapping of the label doesn't work quite correctly.
Here's the colors I have defined:
https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/layers.py#L75-L78

And this is what I see when cycling through the labels (`new_index`/`new_label` is the label after changing the label):
![Screenshot from 2020-05-24 12-07-45](https://user-images.githubusercontent.com/4263537/82751920-e8986200-9dba-11ea-8883-2f0796552885.png)
![Screenshot from 2020-05-24 12-07-54](https://user-images.githubusercontent.com/4263537/82751930-082f8a80-9dbb-11ea-9ce7-b1caaf10e526.png)
![Screenshot from 2020-05-24 12-08-01](https://user-images.githubusercontent.com/4263537/82751944-12ea1f80-9dbb-11ea-8316-8b80c37a1d04.png)
![Screenshot from 2020-05-24 12-08-05](https://user-images.githubusercontent.com/4263537/82751948-18e00080-9dbb-11ea-810c-a6451254237d.png)

So `infected` / 1 is correctly mapped to red and `uncertain` / 3 correctly mapped to yellow,
but the colors for `unlabeled` / 0 and `control` / 2 are swapped.

**Comment by kevinyamauchi** [comment]
Wow, you work fast, @constantinpape ! 

If I understand correctly, the mapping of the `infected_labels` to colors isn't what you're expecting, but the cycling through the `infected_labels` is working. Is that right?

If so, would you mind posting the value of `viewer.layers['infected-vs-control'].face_color_cycle_map` entered into the napari terminal (accessible by the >_ icon in the lower left hand corner of the viewer GUI)? This is the mapping of the property values to colors used for the face color.

Currently, napari assigns the colors to properties in the order given by `numpy.unique()` applied to the property values (see [here](https://github.com/napari/napari/blob/e1e1c44b09c91401ce4a348bbd0f1b3ef6b9ac20/napari/layers/points/points.py#L1035-L1046)). Therefore, the order of the labels you give to the mouse binding function (i.e., the order they are iterated through) may not match the ordering of the colors. I can see why this would unexpected (and frustrating). 

If you've already made your layer and you would like to specify the mapping between property value and face color, you could create a dictionary where they keys are the property values and the values are color (in RGBA numpy arrays) and pass it to the `face_color_cycle_map` property of the layer. Something like:

```python
face_color_cycle_map = {
    'uninfected': np.array([1, 1, 1, 1]),
    'infected': np.array([1, 0, 0, 1])
}

layer.face_color_cycle_map = face_color_cycle_map
layer.refresh_colors()
```

If you'd like to instantiate the layer with a specified color mapping, the easiest way currently is probably to determine the order your property values will appear when using `np.unique()` and then order the face_color_cycle accordingly. I am sorry, it's a bit hacky, but we would have to think a bit on our side before adding the ability to pass in the color map to the init method (i.e., expand the layer API).

Also, it may be most efficient to talk "in person". I am not sure what time zone you're in, but I could hop on a quick video call tomorrow sometime in the afternoon Basel time. If that sounds good, please direct message me on the napari zulip.

By the way, I love all of the feedback! it is super helpful for improving napari.

**Comment by constantinpape** [comment]
> Currently, napari assigns the colors to properties in the order given by `numpy.unique()` applied to the property values (see [here](https://github.com/napari/napari/blob/e1e1c44b09c91401ce4a348bbd0f1b3ef6b9ac20/napari/layers/points/points.py#L1035-L1046)).

Ok, I see. This is what confused me.
I am using numeric labels now to avoid this and then introduced a second list of label names.

I think if you want to support non-numeric properties, they should not be reordered. This is a bit confusing.
But anyway, that's not a concern right now, numeric labels work just as well for me.
Thanks!

> Also, it may be most efficient to talk "in person". I am not sure what time zone you're in, but I could hop on a quick video call tomorrow sometime in the afternoon Basel time. If that sounds good, please direct message me on the napari zulip.

I am in the same timezone, but I think I have the point layer functionality mostly figured out ;).
The only think that is missing is to make the 'on-mouse-click' label switching work,
see https://github.com/hci-unihd/covid-if-annotations/issues/2#issuecomment-633205561.

**Comment by sofroniewn** [comment]
> However, I need to pass the viewer to next_label in next_on_click now, and I don't know what's the best way to do this.
See https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L100-L101 for details.

I think for this you might want to bind the mouse functions to the viewer instead of to the layer and then you'll have access to the viewer and the labels layer. Would that work?

**Comment by constantinpape** [comment]
> I think for this you might want to bind the mouse functions to the viewer instead of to the layer and then you'll have access to the viewer and the labels layer. Would that work?

Yes it works, thanks!

**Comment by constantinpape** [comment]
@sofroniewn @kevinyamauchi 
I have implemented all the functionality necessary for semantic annotations via the points layer now.
Thanks for all your help on this!

**Comment by kevinyamauchi** [comment]
Awesome, nice work!
